### PR TITLE
Fixed: reconnection was only performed in case of the established conection

### PR DESCRIPTION
**Pull request by tiabc**
Hi there!

It looked like a reconnection error. Please, review and accept if this is it.

Regards,
Ivan.

### CODE REVIEW

**Comment by mikemadisonweb** [comment]
Hello Ivan,
This method is a wrapper to the one inside amqp-php library: https://github.com/php-amqplib/php-amqplib/blob/master/PhpAmqpLib/Connection/AbstractConnection.php#L245
That method will throw an error if the connection is not established yet. So, I think that original purpose of it was in a connection renewal, but not in providing fallback on connection failure. 
Thank you for contributing to my extension anyway.

**Comment by tiabc** [comment]
Ok, I see, thanks for the fast answer but it's really non-obvious.

So what would you recommend to utilize the library's capabilities to the full and implement healthcheck in this case? Instantiate a producer and call `setupFabric`?

**Comment by mikemadisonweb** [comment]
setupFabric command is used to create queues and exchanges prior to use by the application(if needed). Producer always opens a new connection, so heartbeat is relevant only for long-running processes, like consumers. This feature is supported by low-level php-amqplib library and can be configured like so:
```
'default' => [
    'host' => '127.0.0.1',
    'port' => '5672',
    'user' => 'your_username',
    'password' => 'your_password',
    'vhost' => '/',
    'connection_timeout' => 3,
    'read_write_timeout' => 3,
    'heartbeat' => 6,
],
```
It's measured in seconds and library maintainers suggest to set the read_write_timeout to 2x the heartbeat to keep socket open.

**Comment by tiabc** [comment]
Thanks for the detailed answer but that's not what I need.

I mean I want to implement healthcheck (a single connection attempt to rmq) without sending any messages and even if setupFabric creates queues and exchanges, that's perfect as they'll be created later anyway.

**Comment by mikemadisonweb** [comment]
This extension use [AMQPLazyConnection](https://github.com/php-amqplib/php-amqplib/blob/master/PhpAmqpLib/Connection/AMQPLazyConnection.php) class, so connection gets established only upon publishing.
The only way I could suggest is to send an empty message to non-existing queue.

**Pull request closed without merging**
